development:
  server: "https://awad-skybnb-zalanfarkas.c9users.io:8081/faye"
  secret_token: "secret"
test:
  server: "https://awad-skybnb-zalanfarkas.c9users.io:8081/faye"
  secret_token: "secret"

production:
  server: "https://messaging-skybnb.herokuapp.com/faye"
  secret_token: 'a4b5a895b6e541379034390009f1c22470f92141586126529574c74e2fa861b1'
  signature_expiration: 3600 # one hour

production2:
  server: "https://awad-skybnb-zalanfarkas.c9users.io:8081/faye"
  secret_token: 'a4b5a895b6e541379034390009f1c22470f92141586126529574c74e2fa861b1'
  signature_expiration: 3600 # one hour